# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocols/trademessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotocols/trademessage.proto\"\xcb\x01\n\x0cOrderMessage\x12\x10\n\x08order_id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x18\n\x04side\x18\x04 \x01(\x0e\x32\n.Direction\x12\x18\n\x10transaction_time\x18\x05 \x01(\x04\x12\x16\n\x0eorder_quantity\x18\x06 \x01(\x02\x12\x1e\n\norder_type\x18\x07 \x01(\x0e\x32\n.OrderType\x12\x12\n\x05price\x18\x08 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_price* \n\tDirection\x12\x08\n\x04LONG\x10\x00\x12\t\n\x05SHORT\x10\x01*\"\n\tOrderType\x12\n\n\x06MARKET\x10\x00\x12\t\n\x05LIMIT\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.trademessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIRECTION._serialized_start=238
  _DIRECTION._serialized_end=270
  _ORDERTYPE._serialized_start=272
  _ORDERTYPE._serialized_end=306
  _ORDERMESSAGE._serialized_start=33
  _ORDERMESSAGE._serialized_end=236
# @@protoc_insertion_point(module_scope)
