name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build ./matching-engine/ -t arcanefz/trade-messaging-service:latest
          docker build ./trade-messaging-service/ -t arcanefz/matching-engine:latest
        
      - name: Login to Docker Hub
        run: |
          docker login -u arcanefz -p ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Push images to Docker Hub
        run: |
          docker push arcanefz/trade-messaging-service:latest
          docker push arcanefz/matching-engine:latest 

